### ISSUE TITLE
alternative to termios dependency

### ISSUE THREAD

**Issue by notyettested** [NetApp/recline#4]
hi,

so im trying to get it to run in pycharm on windows which needs termios and termios is Linux only...
i´d normally just switch over to Linux but the finished tool has to work on both so i can´t realy do that here.

is it possible to substitute termios for windows or have a version with some more compatible library? i´d be fine with using 2 seperate libraries for Linux and Windows if this allows me to have it work properly.

**Comment by RobertBlackhart** [comment]
You're right, this does not currently run under windows. There are two things that stop it from working immediately:

1. It relies on the readline module, which isn't part of the Windows build of Python. This could be overcome by listing pyreadline as a prerequisite for the Windows platform.
2. It relies on the curses module, which again isn't part of the Windows build of Python. This one is more difficult to replace. I think the solution would be to replace the use of curses with some other library that does the same sort of thing but also works on Windows. I'll have to look into that. In the short term, it could be possible to just try/except the import of curses and if it can't be found, disable the man page feature while allowing the rest of the library to work.

I'll try playing with these a bit and see what I can come up with.

**Comment by RobertBlackhart** [comment]
On point 2 above, the `windows-curses` package seems to work fine, so that's good.

There didn't seem to be a good alternative for the termios module. This is probably OK, I just commented out the one place that used it, and for most cases it shouldn't be a big deal.

There's also no ability to handle the SIGQUIT signal in Windows. This means that you can't start the debugger inside the application by pressign `ctrl+\` like you can on unix. This feature is not essential though and you can always put a breakpoint in code.

There's no ability to handle the SIGTSTP signal in Windows either. This means that async commands don't work quite the same since you can't put them in the background while they are already running. You can start a command in the background when you execute it with `-background`, but if you start it in the foreground (the default), you can't send it to the background.

**Comment by RobertBlackhart** [comment]
I've released version 2021.4 which should work around the issues you were having. Please test it and let me know if you run into additional issues (probably in a separate issue).
